AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for image-process-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 50
    MemorySize: 1000

Resources:
  ThumbnailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Role: "arn:aws:iam::746167823857:role/lambda-ex"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./thumbnail
      DockerTag: python3.8-v1
  FaceDetectionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Role: "arn:aws:iam::746167823857:role/lambda-ex"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./face_detection
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ThumbnailFunction:
    Description: "Thumbnail Lambda Function ARN"
    Value: !GetAtt ThumbnailFunction.Arn
  FaceDetectionFunction:
    Description: "Face Detection Lambda Function ARN"
    Value: !GetAtt FaceDetectionFunction.Arn